name: Python-Lint

on:
  workflow_dispatch: 

jobs:
  Python_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cone the code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Linter
        run: pip install ruff
      - name: Check file using Liting
        run: ruff check . --fix
